namespace CVPlatform.Web.Localization;

public static class UiStrings
{
    private static readonly Dictionary<string, Dictionary<string, string>> Values = new()
    {
        ["en"] = new()
        {
            ["Nav.Positions"] = "Positions",
            ["Nav.Profile"] = "Profile",
            ["Nav.MyCvs"] = "My CVs",
            ["Nav.Attributes"] = "Attributes",
            ["Nav.BrowseCvs"] = "Browse CVs",

            ["Positions.Title"] = "Positions",
            ["Positions.New"] = "New Position",
            ["Positions.Company"] = "Company",
            ["Positions.Level"] = "Level",
            ["Positions.Access"] = "Access",
            ["Positions.Discussion"] = "Discussion",

            ["Positions.SearchPlaceholder"] = "Search positions...",
            ["Positions.CvCount"] = "CVs",
            ["Positions.Created"] = "Created",
            ["Positions.NoResults"] = "No positions found.",
            ["Positions.SelectRowHint"] = "Select a position to open, edit, duplicate or delete it.",
            ["AccessMode.Public"] = "Public",
            ["AccessMode.Restricted"] = "Restricted",
            ["PositionLevel.Junior"] = "Junior",
            ["PositionLevel.Middle"] = "Middle",
            ["PositionLevel.Senior"] = "Senior",
            ["PositionLevel.CLevel"] = "C-Level",

            ["Positions.EditTitle"] = "Edit Position",
            ["Positions.FormTitle"] = "Title",
            ["Positions.FormDescription"] = "Short Description",
            ["Positions.AccessModeLabel"] = "Access Mode",
            ["Positions.BasicInfo"] = "Basic Information",
            ["Positions.AttributeTemplate"] = "Attribute Template",
            ["Positions.SearchAttributes"] = "Search attributes...",
            ["Positions.SelectedAttributes"] = "Selected Attributes",
            ["Positions.NoAttributesSelected"] = "No attributes selected yet.",
            ["Positions.AccessRules"] = "Access Rules",
            ["Positions.AccessRulesHint"] = "Only candidates whose profile values satisfy every rule below can access this position.",
            ["Positions.AddRule"] = "Add Rule",
            ["Positions.ProjectFilters"] = "Project Filters",
            ["Positions.RequiredTags"] = "Required Project Tags",
            ["Positions.MaxProjects"] = "Max Projects in CV",
            ["Positions.Required"] = "Required",


            ["Attributes.Title"] = "Attribute Library",
            ["Attributes.New"] = "New Attribute",
            ["Attributes.Name"] = "Name",
            ["Attributes.Category"] = "Category",
            ["Attributes.Type"] = "Type",
            ["Attributes.BuiltIn"] = "Built-in",
            ["Attributes.Options"] = "Options",
            ["Attributes.SearchPlaceholder"] = "Search attributes...",
            ["Attributes.AllCategories"] = "All Categories",
            ["Attributes.NoResults"] = "No attributes found.",
            ["Attributes.SelectRowHint"] = "Select an attribute to edit or delete it.",
            ["Attributes.BuiltInHint"] = "Built-in attributes cannot be edited or deleted.",
            ["Attributes.Edit"] = "Edit Attribute",
            ["Attributes.FormHeading"] = "Attribute Details",
            ["Attributes.Description"] = "Description",
            ["Attributes.OptionsLabel"] = "Dropdown Options",
            ["Attributes.OptionsHint"] = "Separate options with commas. At least two options are required.",

            ["AttributeType.SingleLineText"] = "Single-line Text",
            ["AttributeType.MarkdownText"] = "Markdown Text",
            ["AttributeType.Image"] = "Image",
            ["AttributeType.Numeric"] = "Numeric",
            ["AttributeType.Date"] = "Date",
            ["AttributeType.DateRange"] = "Period",
            ["AttributeType.Boolean"] = "Boolean",
            ["AttributeType.Dropdown"] = "Dropdown",

            ["Profile.Me"] = "Me",
            ["Profile.Info"] = "Info",
            ["Profile.Projects"] = "Projects",
            ["Profile.FirstName"] = "First Name",
            ["Profile.LastName"] = "Last Name",
            ["Profile.Location"] = "Location",
            ["Profile.PhotoUrl"] = "Photo URL",
            ["Profile.SaveStatusSaved"] = "Saved",
            ["Profile.AddAttribute"] = "Add",
            ["Profile.Remove"] = "Remove",
            ["Profile.NewProject"] = "New Project",
            ["Profile.ProjectName"] = "Name",
            ["Profile.Period"] = "Period",
            ["Profile.Tags"] = "Tags",
            ["Profile.Present"] = "Present",
            ["Profile.Description"] = "Description (Markdown)",
            ["Profile.TechnologyTags"] = "Technology Tags (comma separated)",
            ["Profile.TotalCvs"] = "Total CVs",
            ["Profile.PublishedCvs"] = "Published",
            ["Profile.AttributesFilled"] = "Attributes Filled",
            ["Profile.NoLocationSet"] = "Location not set",
            ["Profile.SavingStatus"] = "Saving...",
            ["Profile.SavedJustNow"] = "All changes saved",
            ["Profile.RecentlyUsed"] = "Recently used:",
            ["Profile.SearchAttributePlaceholder"] = "Search attribute library...",
            ["Profile.NoAttributesYet"] = "You haven't added any attributes yet.",
            ["Profile.NoProjectsYet"] = "You haven't added any projects yet.",
            ["Profile.DeleteProjectConfirm"] = "Delete this project? This cannot be undone.",
            ["Profile.EditProjectTitle"] = "Edit Project",
            ["Profile.SelectAttributePrompt"] = "-- select an attribute --",
            ["Profile.BackToProjects"] = "Back to Projects",

            ["Crm.SyncToCrm"] = "Sync to CRM",
            ["Crm.Company"] = "Company",
            ["Crm.JobTitle"] = "Job Title",
            ["Crm.Phone"] = "Phone",
            ["Crm.Email"] = "Email",
            ["Crm.MarketingOptIn"] = "Receive marketing communications",
            ["Crm.Submit"] = "Sync to Salesforce",
            ["Crm.AlreadySynced"] = "Previously Synced to Salesforce",
            ["Crm.SyncedStatus"] = "Synced",
            ["Crm.AccountId"] = "Salesforce Account ID",
            ["Crm.ContactId"] = "Salesforce Contact ID",
            ["Crm.SyncedAt"] = "Last Synced At",
            ["Crm.SyncSuccess"] = "Successfully synced to Salesforce! Account ID: {0}, Contact ID: {1}",
            ["Crm.SyncFailed"] = "Failed to sync to Salesforce.",

            ["Cvs.Title"] = "My CVs",
            ["Cvs.New"] = "New CV",
            ["Cvs.ChoosePosition"] = "Choose a Position",
            ["Cvs.NoPositionsAvailable"] = "No positions are currently available for you.",
            ["Cvs.Create"] = "Create CV",
            ["Cvs.Status"] = "Status",
            ["Cvs.Created"] = "Created",
            ["Cvs.Published"] = "Published",
            ["Cvs.Open"] = "Open",
            ["Cvs.AttributesHeading"] = "Attributes",
            ["Cvs.ProjectsHeading"] = "Projects",
            ["Cvs.Publish"] = "Publish",
            ["Cvs.ConfirmDelete"] = "Delete this CV?",

            ["RecruiterCvs.Title"] = "Browse CVs",
            ["RecruiterCvs.AllPositions"] = "All Positions",
            ["RecruiterCvs.SearchPlaceholder"] = "Search candidate or position",
            ["RecruiterCvs.Search"] = "Search",
            ["RecruiterCvs.Candidate"] = "Candidate",
            ["RecruiterCvs.Position"] = "Position",
            ["RecruiterCvs.Likes"] = "Likes",
            ["RecruiterCvs.NoResults"] = "No published CVs found.",
            ["RecruiterCvs.SelectRowHint"] = "Select a row to open the full CV.",
            ["RecruiterCvs.ViewCv"] = "View CV",
            ["RecruiterCvs.BackToList"] = "Back to list",
            ["RecruiterCvs.CvInformation"] = "CV Information",

            ["CvStatus.Draft"] = "Draft",
            ["CvStatus.Published"] = "Published",

            ["Discussions.Title"] = "Discussion",
            ["Discussions.Placeholder"] = "Write a comment (Markdown supported)",
            ["Discussions.Post"] = "Post",
            ["Discussions.Empty"] = "No posts yet. Start the conversation.",
            ["Discussions.SendHint"] = "Markdown supported. Press Ctrl + Enter to post.",
            ["Discussions.SendError"] = "Your message could not be sent. Please try again.",
            ["Positions.Overview"] = "Overview",
            ["Positions.BackToList"] = "Back to positions",
            ["Positions.CreateCv"] = "Create CV",
            ["Positions.PublicHint"] = "This position is public. Every signed-in user can access it.",
            ["Positions.NoRules"] = "No access rules are configured.",
            ["Positions.RuleAttribute"] = "Attribute",
            ["Positions.RuleCondition"] = "Condition",
            ["Positions.RuleValue"] = "Value",
            ["Positions.NoProjectFilters"] = "No project filters. All of the candidate's projects are used, most recent first.",
            ["Positions.AllTagsRequired"] = "A project must have all of these tags to appear in the CV.",
            ["Positions.SelectRowHintView"] = "Select a position to open its details.",
            ["RuleOperator.Contains"] = "contains",
            ["Common.Open"] = "Open",

            ["Common.Edit"] = "Edit",
            ["Common.Delete"] = "Delete",
            ["Common.Duplicate"] = "Duplicate",
            ["Common.Save"] = "Save",
            ["Common.Cancel"] = "Cancel",
            ["Common.Remove"] = "Remove",

            ["Common.Search"] = "Search",
            ["Common.Refresh"] = "Refresh",
            ["Common.ConfirmDelete"] = "Are you sure you want to delete this? This cannot be undone.",

            ["Nav.Dashboard"] = "Dashboard",
            ["Nav.Users"] = "Users",
            ["Users.Title"] = "User Management",
            ["Users.SearchPlaceholder"] = "Search by name or email...",
            ["Users.AllRoles"] = "All Roles",
            ["Users.Name"] = "Name",
            ["Users.Email"] = "Email",
            ["Users.Role"] = "Role",
            ["Users.Confirmed"] = "Email Confirmed",
            ["Users.Status"] = "Status",
            ["Users.Active"] = "Active",
            ["Users.Blocked"] = "Blocked",
            ["Users.NoResults"] = "No users found.",
            ["Users.SelectRowHint"] = "Select a user to view their profile or CVs, change their role, or block and delete them.",
            ["Users.SelfHint"] = "This is your own account. You cannot block or delete it.",
            ["Users.ViewProfile"] = "View Profile",
            ["Users.ViewCvs"] = "View CVs",
            ["Users.AssignRole"] = "Assign Role",
            ["Users.Block"] = "Block",
            ["Users.Unblock"] = "Unblock",
            ["Users.ConfirmDelete"] = "Delete this user permanently? Their profile, projects and CVs will be removed. This cannot be undone.",
            ["Users.RoleAssigned"] = "Role updated.",
            ["Users.UserBlocked"] = "User blocked.",
            ["Users.UserUnblocked"] = "User unblocked.",
            ["Users.UserDeleted"] = "User deleted.",
            ["Role.Candidate"] = "Candidate",
            ["Role.Recruiter"] = "Recruiter",
            ["Role.Administrator"] = "Administrator",
            ["Common.Yes"] = "Yes",
            ["Common.No"] = "No",
            ["Nav.Logout"] = "Logout",

            ["Common.SearchPlaceholder"] = "Search everything...",
            ["Common.LightMode"] = "Light Mode",
            ["Common.DarkMode"] = "Dark Mode",
            ["Common.Notifications"] = "Notifications",
            ["Common.Language"] = "Change language",

            ["Dashboard.Cvs24h"] = "CVs (24h)",
            ["Dashboard.TotalPositions"] = "Total Positions",
            ["Dashboard.TotalCandidates"] = "Candidates",
            ["Dashboard.TotalRecruiters"] = "Recruiters",
            ["Dashboard.TotalCvs"] = "Total CVs",
            ["Dashboard.LatestPositions"] = "Latest Positions",
            ["Dashboard.PopularPositions"] = "Most Popular Positions",
            ["Dashboard.TagCloud"] = "Technology Tag Cloud",
            ["Dashboard.CvsSubmitted"] = "CVs Submitted",
            ["Dashboard.NoData"] = "No data yet",
        },
        ["bn"] = new()
        {
            ["Nav.Positions"] = "পজিশন",
            ["Nav.Profile"] = "প্রোফাইল",
            ["Nav.MyCvs"] = "আমার সিভি",
            ["Nav.Attributes"] = "অ্যাট্রিবিউট",
            ["Nav.BrowseCvs"] = "সিভি দেখুন",

            ["Positions.Title"] = "পজিশনসমূহ",
            ["Positions.New"] = "নতুন পজিশন",
            ["Positions.Company"] = "কোম্পানি",
            ["Positions.Level"] = "লেভেল",
            ["Positions.Access"] = "অ্যাক্সেস",
            ["Positions.Discussion"] = "আলোচনা",

            ["Positions.SearchPlaceholder"] = "পজিশন খুঁজুন...",
            ["Positions.CvCount"] = "সিভি",
            ["Positions.Created"] = "তৈরি হয়েছে",
            ["Positions.NoResults"] = "কোনো পজিশন পাওয়া যায়নি।",
            ["Positions.SelectRowHint"] = "খুলতে, সম্পাদনা, কপি বা মুছে ফেলতে একটি পজিশন নির্বাচন করুন।",
            ["AccessMode.Public"] = "পাবলিক",
            ["AccessMode.Restricted"] = "রেস্ট্রিক্টেড",
            ["PositionLevel.Junior"] = "জুনিয়র",
            ["PositionLevel.Middle"] = "মিডল",
            ["PositionLevel.Senior"] = "সিনিয়র",
            ["PositionLevel.CLevel"] = "সি-লেভেল",

            ["Positions.EditTitle"] = "পজিশন সম্পাদনা",
            ["Positions.FormTitle"] = "শিরোনাম",
            ["Positions.FormDescription"] = "সংক্ষিপ্ত বিবরণ",
            ["Positions.AccessModeLabel"] = "অ্যাক্সেস মোড",
            ["Positions.BasicInfo"] = "মৌলিক তথ্য",
            ["Positions.AttributeTemplate"] = "অ্যাট্রিবিউট টেমপ্লেট",
            ["Positions.SearchAttributes"] = "অ্যাট্রিবিউট খুঁজুন...",
            ["Positions.SelectedAttributes"] = "নির্বাচিত অ্যাট্রিবিউট",
            ["Positions.NoAttributesSelected"] = "এখনো কোনো অ্যাট্রিবিউট নির্বাচন করা হয়নি।",
            ["Positions.AccessRules"] = "অ্যাক্সেস রুলস",
            ["Positions.AccessRulesHint"] = "নিচের প্রতিটি রুল পূরণ করা ক্যান্ডিডেটরাই কেবল এই পজিশনে অ্যাক্সেস পাবে।",
            ["Positions.AddRule"] = "রুল যোগ করুন",
            ["Positions.ProjectFilters"] = "প্রজেক্ট ফিল্টার",
            ["Positions.RequiredTags"] = "আবশ্যক প্রজেক্ট ট্যাগ",
            ["Positions.MaxProjects"] = "সিভিতে সর্বোচ্চ প্রজেক্ট",
            ["Positions.Required"] = "আবশ্যক",

            ["Attributes.Title"] = "অ্যাট্রিবিউট লাইব্রেরি",
            ["Attributes.New"] = "নতুন অ্যাট্রিবিউট",
            ["Attributes.Name"] = "নাম",
            ["Attributes.Category"] = "ক্যাটাগরি",
            ["Attributes.Type"] = "টাইপ",
            ["Attributes.BuiltIn"] = "বিল্ট-ইন",
            ["Attributes.Options"] = "অপশন",
            ["Attributes.SearchPlaceholder"] = "অ্যাট্রিবিউট খুঁজুন...",
            ["Attributes.AllCategories"] = "সব ক্যাটাগরি",
            ["Attributes.NoResults"] = "কোনো অ্যাট্রিবিউট পাওয়া যায়নি।",
            ["Attributes.SelectRowHint"] = "সম্পাদনা বা মুছে ফেলতে একটি অ্যাট্রিবিউট নির্বাচন করুন।",
            ["Attributes.BuiltInHint"] = "বিল্ট-ইন অ্যাট্রিবিউট সম্পাদনা বা মুছে ফেলা যাবে না।",
            ["Attributes.Edit"] = "অ্যাট্রিবিউট সম্পাদনা",
            ["Attributes.FormHeading"] = "অ্যাট্রিবিউটের বিবরণ",
            ["Attributes.Description"] = "বর্ণনা",
            ["Attributes.OptionsLabel"] = "ড্রপডাউন অপশন",
            ["Attributes.OptionsHint"] = "অপশনগুলো কমা (,) দিয়ে আলাদা করুন। কমপক্ষে দুটি অপশন দিতে হবে।",

            ["AttributeType.SingleLineText"] = "সিঙ্গেল-লাইন টেক্সট",
            ["AttributeType.MarkdownText"] = "মার্কডাউন টেক্সট",
            ["AttributeType.Image"] = "ছবি",
            ["AttributeType.Numeric"] = "সংখ্যা",
            ["AttributeType.Date"] = "তারিখ",
            ["AttributeType.DateRange"] = "সময়কাল",
            ["AttributeType.Boolean"] = "বুলিয়ান",
            ["AttributeType.Dropdown"] = "ড্রপডাউন",

            ["Profile.Me"] = "আমি",
            ["Profile.Info"] = "তথ্য",
            ["Profile.Projects"] = "প্রজেক্ট",
            ["Profile.FirstName"] = "প্রথম নাম",
            ["Profile.LastName"] = "শেষ নাম",
            ["Profile.Location"] = "অবস্থান",
            ["Profile.PhotoUrl"] = "ছবির URL",
            ["Profile.SaveStatusSaved"] = "সংরক্ষিত হয়েছে",
            ["Profile.AddAttribute"] = "যোগ করুন",
            ["Profile.Remove"] = "মুছে ফেলুন",
            ["Profile.NewProject"] = "নতুন প্রজেক্ট",
            ["Profile.ProjectName"] = "নাম",
            ["Profile.Period"] = "সময়কাল",
            ["Profile.Tags"] = "ট্যাগ",
            ["Profile.Present"] = "বর্তমান",
            ["Profile.Description"] = "বিবরণ (মার্কডাউন)",
            ["Profile.TechnologyTags"] = "টেকনোলজি ট্যাগ (কমা দিয়ে আলাদা)",
            ["Profile.TotalCvs"] = "মোট সিভি",
            ["Profile.PublishedCvs"] = "প্রকাশিত",
            ["Profile.AttributesFilled"] = "পূরণকৃত অ্যাট্রিবিউট",
            ["Profile.NoLocationSet"] = "অবস্থান দেওয়া নেই",
            ["Profile.SavingStatus"] = "সংরক্ষণ হচ্ছে...",
            ["Profile.SavedJustNow"] = "সব পরিবর্তন সংরক্ষিত হয়েছে",
            ["Profile.RecentlyUsed"] = "সম্প্রতি ব্যবহৃত:",
            ["Profile.SearchAttributePlaceholder"] = "অ্যাট্রিবিউট লাইব্রেরি খুঁজুন...",
            ["Profile.NoAttributesYet"] = "তুমি এখনো কোনো অ্যাট্রিবিউট যোগ করোনি।",
            ["Profile.NoProjectsYet"] = "তুমি এখনো কোনো প্রজেক্ট যোগ করোনি।",
            ["Profile.DeleteProjectConfirm"] = "এই প্রজেক্টটি মুছে ফেলবে? এটি ফিরিয়ে আনা যাবে না।",
            ["Profile.EditProjectTitle"] = "প্রজেক্ট সম্পাদনা",
            ["Profile.SelectAttributePrompt"] = "-- একটি অ্যাট্রিবিউট নির্বাচন করো --",
            ["Profile.BackToProjects"] = "প্রজেক্টে ফিরে যাও",

            ["Crm.SyncToCrm"] = "সিআরএম-এ সিঙ্ক করুন",
            ["Crm.Company"] = "কোম্পানি",
            ["Crm.JobTitle"] = "কাজের পদবী",
            ["Crm.Phone"] = "ফোন",
            ["Crm.Email"] = "ইমেইল",
            ["Crm.MarketingOptIn"] = "মার্কেটিং যোগাযোগ পেতে সম্মত",
            ["Crm.Submit"] = "সেলসফোর্সে সিঙ্ক করুন",
            ["Crm.AlreadySynced"] = "পূর্বে সেলসফোর্সে সিঙ্ক করা হয়েছে",
            ["Crm.SyncedStatus"] = "সিঙ্ক হয়েছে",
            ["Crm.AccountId"] = "সেলসফোর্স অ্যাকাউন্ট আইডি",
            ["Crm.ContactId"] = "সেলসফোর্স কন্টাক্ট আইডি",
            ["Crm.SyncedAt"] = "সর্বশেষ সিঙ্কের সময়",
            ["Crm.SyncSuccess"] = "সফলভাবে সেলসফোর্সে সিঙ্ক হয়েছে! অ্যাকাউন্ট আইডি: {0}, কন্টাক্ট আইডি: {1}",
            ["Crm.SyncFailed"] = "সেলসফোর্সে সিঙ্ক করতে ব্যর্থ হয়েছে।",

            ["Cvs.Title"] = "আমার সিভি",
            ["Cvs.New"] = "নতুন সিভি",
            ["Cvs.ChoosePosition"] = "একটি পজিশন নির্বাচন করুন",
            ["Cvs.NoPositionsAvailable"] = "আপনার জন্য এই মুহূর্তে কোনো পজিশন উপলব্ধ নেই।",
            ["Cvs.Create"] = "সিভি তৈরি করুন",
            ["Cvs.Status"] = "অবস্থা",
            ["Cvs.Created"] = "তৈরি হয়েছে",
            ["Cvs.Published"] = "প্রকাশিত",
            ["Cvs.Open"] = "খুলুন",
            ["Cvs.AttributesHeading"] = "অ্যাট্রিবিউট",
            ["Cvs.ProjectsHeading"] = "প্রজেক্ট",
            ["Cvs.Publish"] = "প্রকাশ করুন",
            ["Cvs.ConfirmDelete"] = "এই সিভিটি মুছে ফেলবেন?",

            ["RecruiterCvs.Title"] = "সিভি ব্রাউজ করুন",
            ["RecruiterCvs.AllPositions"] = "সব পজিশন",
            ["RecruiterCvs.SearchPlaceholder"] = "প্রার্থী বা পজিশন খুঁজুন",
            ["RecruiterCvs.Search"] = "খুঁজুন",
            ["RecruiterCvs.Candidate"] = "প্রার্থী",
            ["RecruiterCvs.Position"] = "পজিশন",
            ["RecruiterCvs.Likes"] = "লাইক",
            ["RecruiterCvs.NoResults"] = "কোনো প্রকাশিত সিভি পাওয়া যায়নি।",
            ["RecruiterCvs.SelectRowHint"] = "সম্পূর্ণ সিভি খুলতে একটি সারি নির্বাচন করুন।",
            ["RecruiterCvs.ViewCv"] = "সিভি দেখুন",
            ["RecruiterCvs.BackToList"] = "তালিকায় ফিরে যান",
            ["RecruiterCvs.CvInformation"] = "সিভি তথ্য",

            ["CvStatus.Draft"] = "খসড়া",
            ["CvStatus.Published"] = "প্রকাশিত",

            ["Discussions.Title"] = "আলোচনা",
            ["Discussions.Placeholder"] = "মন্তব্য লিখুন (মার্কডাউন সমর্থিত)",
            ["Discussions.Post"] = "পোস্ট করুন",
            ["Discussions.Empty"] = "এখনো কোনো পোস্ট নেই। আলোচনা শুরু করুন।",
            ["Discussions.SendHint"] = "মার্কডাউন সমর্থিত। পোস্ট করতে Ctrl + Enter চাপুন।",
            ["Discussions.SendError"] = "আপনার বার্তা পাঠানো যায়নি। আবার চেষ্টা করুন।",
            ["Positions.Overview"] = "সংক্ষিপ্ত বিবরণ",
            ["Positions.BackToList"] = "পজিশন তালিকায় ফিরুন",
            ["Positions.CreateCv"] = "সিভি তৈরি করুন",
            ["Positions.PublicHint"] = "এই পজিশনটি পাবলিক। সাইন-ইন করা যেকোনো ব্যবহারকারী এতে প্রবেশ করতে পারবেন।",
            ["Positions.NoRules"] = "কোনো অ্যাক্সেস রুল নির্ধারণ করা নেই।",
            ["Positions.RuleAttribute"] = "অ্যাট্রিবিউট",
            ["Positions.RuleCondition"] = "শর্ত",
            ["Positions.RuleValue"] = "মান",
            ["Positions.NoProjectFilters"] = "কোনো প্রজেক্ট ফিল্টার নেই। প্রার্থীর সব প্রজেক্ট, নতুনগুলো আগে, ব্যবহার করা হবে।",
            ["Positions.AllTagsRequired"] = "সিভিতে আসতে হলে একটি প্রজেক্টে এই সবগুলো ট্যাগ থাকতে হবে।",
            ["Positions.SelectRowHintView"] = "বিস্তারিত দেখতে একটি পজিশন নির্বাচন করুন।",
            ["RuleOperator.Contains"] = "ধারণ করে",
            ["Common.Open"] = "খুলুন",

            ["Common.Edit"] = "সম্পাদনা",
            ["Common.Delete"] = "মুছে ফেলুন",
            ["Common.Duplicate"] = "কপি করুন",
            ["Common.Save"] = "সংরক্ষণ করুন",
            ["Common.Cancel"] = "বাতিল",
            ["Common.Remove"] = "সরান",
            ["Common.Search"] = "খুঁজুন",
            ["Common.Refresh"] = "রিফ্রেশ",
            ["Common.ConfirmDelete"] = "তুমি কি নিশ্চিত মুছে ফেলতে চাও? এটি ফিরিয়ে আনা যাবে না।",

            ["Nav.Dashboard"] = "ড্যাশবোর্ড",
            ["Nav.Users"] = "ব্যবহারকারী",
            ["Users.Title"] = "ব্যবহারকারী ব্যবস্থাপনা",
            ["Users.SearchPlaceholder"] = "নাম বা ইমেইল দিয়ে খুঁজুন...",
            ["Users.AllRoles"] = "সব রোল",
            ["Users.Name"] = "নাম",
            ["Users.Email"] = "ইমেইল",
            ["Users.Role"] = "রোল",
            ["Users.Confirmed"] = "ইমেইল নিশ্চিত",
            ["Users.Status"] = "অবস্থা",
            ["Users.Active"] = "সক্রিয়",
            ["Users.Blocked"] = "ব্লক করা",
            ["Users.NoResults"] = "কোনো ব্যবহারকারী পাওয়া যায়নি।",
            ["Users.SelectRowHint"] = "প্রোফাইল বা সিভি দেখতে, রোল পরিবর্তন করতে, অথবা ব্লক ও মুছে ফেলতে একজন ব্যবহারকারী নির্বাচন করুন।",
            ["Users.SelfHint"] = "এটি আপনার নিজের অ্যাকাউন্ট। এটি ব্লক বা মুছে ফেলা যাবে না।",
            ["Users.ViewProfile"] = "প্রোফাইল দেখুন",
            ["Users.ViewCvs"] = "সিভি দেখুন",
            ["Users.AssignRole"] = "রোল দিন",
            ["Users.Block"] = "ব্লক করুন",
            ["Users.Unblock"] = "আনব্লক করুন",
            ["Users.ConfirmDelete"] = "এই ব্যবহারকারীকে স্থায়ীভাবে মুছে ফেলবেন? তার প্রোফাইল, প্রজেক্ট ও সিভি মুছে যাবে। এটি ফিরিয়ে আনা যাবে না।",
            ["Users.RoleAssigned"] = "রোল আপডেট হয়েছে।",
            ["Users.UserBlocked"] = "ব্যবহারকারীকে ব্লক করা হয়েছে।",
            ["Users.UserUnblocked"] = "ব্যবহারকারীকে আনব্লক করা হয়েছে।",
            ["Users.UserDeleted"] = "ব্যবহারকারীকে মুছে ফেলা হয়েছে।",
            ["Role.Candidate"] = "প্রার্থী",
            ["Role.Recruiter"] = "রিক্রুটার",
            ["Role.Administrator"] = "অ্যাডমিনিস্ট্রেটর",
            ["Common.Yes"] = "হ্যাঁ",
            ["Common.No"] = "না",
            ["Nav.Logout"] = "লগ আউট",

            ["Common.SearchPlaceholder"] = "সব কিছু খুঁজুন...",
            ["Common.LightMode"] = "লাইট মোড",
            ["Common.DarkMode"] = "ডার্ক মোড",
            ["Common.Notifications"] = "নোটিফিকেশন",
            ["Common.Language"] = "ভাষা পরিবর্তন",

            ["Dashboard.Cvs24h"] = "সিভি (২৪ ঘণ্টা)",
            ["Dashboard.TotalPositions"] = "মোট পজিশন",
            ["Dashboard.TotalCandidates"] = "প্রার্থী",
            ["Dashboard.TotalRecruiters"] = "রিক্রুটার",
            ["Dashboard.TotalCvs"] = "মোট সিভি",
            ["Dashboard.LatestPositions"] = "সাম্প্রতিক পজিশন",
            ["Dashboard.PopularPositions"] = "জনপ্রিয় পজিশন",
            ["Dashboard.TagCloud"] = "টেকনোলজি ট্যাগ ক্লাউড",
            ["Dashboard.CvsSubmitted"] = "জমাকৃত সিভি",
            ["Dashboard.NoData"] = "এখনো কোনো তথ্য নেই",
        }
    };

    public static string Get(string culture, string key)
    {
        var lang = culture.StartsWith("bn") ? "bn" : "en";
        return Values[lang].TryGetValue(key, out var value) ? value : key;
    }
}